[build]
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20.15.0"

[build.system_packages]
  packages = ["unixodbc-dev", "g++", "make", "python3"]
